[package]
name = "getting_started"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.51"
image = "0.24"

[dependencies.glad]
path = "../glad"
version = "*"

[dependencies.common]
path = "../common"
version = "*"
